export type ThumbnailAttribution = {
  photographer: string
  photographer_url: string
}

export type FullPostType = {
  title: string
  body: string
  slug: string
  category: string
  tags: string[]
  thumbnailUrl?: string
  thumbnailAttribution?: ThumbnailAttribution | null
  autoGenerated: boolean
  createdAt: { seconds: number }
  publishedAt: { seconds: number }
  clickCount: number
  readCount: number
  variantId: string
  testTarget: string[]
}
export type Post = FullPostType & {
  id: string
}
