export type ThumbnailAttribution = {
  photographer: string
  photographer_url: string
}

export type FullPostType = {
  title: string
  body: string
  slug: string
  category: string
  tags: string[]
  keyword?: string

  thumbnailUrl?: string
  thumbnailAttribution?: ThumbnailAttribution | null

  autoGenerated: boolean
  createdAt: { seconds: number }
  publishedAt: { seconds: number }
  updatedAt?: { seconds: number }

  publishedAtTimestamp?: number
  clickCount: number
  readCount: number
  variantId: string
  testTarget: string[]

  source?: string // auto/manual の区別
  score?: number
  wordCount?: number
  internalLinks?: string[]
}

export type Post = FullPostType & {
  id: string
}

export type GeneratedPost = {
  title: string
  body: string
  category: string
  tags: string[]
  thumbnailKeywords: string
  internalLinks: string[]
}
