'use client'

import { useEffect, useState } from 'react'
import { collection, getDocs } from 'firebase/firestore'
import { db } from '../firebase'

export type Post = {
  id: string
  title: string
  body: string
  slug: string
  category?: string
  tags?: string[]
  thumbnailUrl?: string
  thumbnailAttribution?: {
    photographer: string
    photographer_url: string
  }
  variantId?: string // A/Bテスト識別用
  testTarget?: string[] // テスト対象項目（例：['title']）
  readCount?: number // 閲覧数
  clickCount?: number // CTAクリック数
  publishedAt?: { seconds: number } // 公開日時（予約投稿などにも使える）
  autoGenerated?: boolean // AI生成記事かどうか
  createdAt: { seconds: number }
}

// 👇 usePosts を明示的に export
export const usePosts = () => {
  const [posts, setPosts] = useState<Post[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const fetchData = async () => {
      const snapshot = await getDocs(collection(db, 'posts'))
      const data = snapshot.docs.map((doc) => ({
        id: doc.id,
        ...(doc.data() as Omit<Post, 'id'>),
      }))
      setPosts(data)
      setLoading(false)
    }

    fetchData()
  }, [])

  return { posts, loading }
}
