import { NextResponse } from 'next/server'
import { generatePostByKeyword } from '@/lib/openai/generatePostByKeyword'
import { savePost } from '@/lib/firestore/savePost'
import { generateSlug } from '@/lib/utils/slug'

export async function POST(req: Request) {
  const { keyword } = await req.json()

  try {
    // OpenAIで投稿を生成
    const post = await generatePostByKeyword(keyword)

    // Firestoreに保存
    await savePost({
      ...post,
      slug: generateSlug(post.title), // タイトルから slug 生成
      keyword,
      thumbnailUrl: '',
      thumbnailAttribution: null,
      autoGenerated: true,
      createdAt: { seconds: Math.floor(Date.now() / 1000) },
      publishedAt: { seconds: Math.floor(Date.now() / 1000) },
      clickCount: 0,
      readCount: 0,
      variantId: '',
      testTarget: [],
      id: '', // Firestore 側で自動生成される場合は空でもOK
    })

    return NextResponse.json(post)
  } catch (error) {
    console.error('🔥 投稿生成エラー:', error)
    return NextResponse.json(
      { error: (error as Error).message },
      { status: 500 }
    )
  }
}
