import { db } from '../firebase'
import { collection, query, where, getDocs } from 'firebase/firestore'
import type { Post } from '@/types/post'

export const getPostBySlug = async (slug: string): Promise<Post | null> => {
  const q = query(collection(db, 'posts'), where('slug', '==', slug))
  const snapshot = await getDocs(q)

  if (snapshot.empty) return null

  const doc = snapshot.docs[0]
  const data = doc.data()

  return {
    id: doc.id,
    title: data.title,
    body: data.body,
    slug: data.slug,
    category: data.category,
    tags: data.tags,
    thumbnailUrl: data.thumbnailUrl,
    thumbnailAttribution: data.thumbnailAttribution ?? null,
    createdAt: data.createdAt,
    publishedAt: data.publishedAt ?? data.createdAt,
    autoGenerated: data.autoGenerated ?? false,
    clickCount: data.clickCount ?? 0,
    readCount: data.readCount ?? 0,
    variantId: data.variantId ?? 'A',
    testTarget: data.testTarget ?? [],
  }
}
