import { google } from 'googleapis'
import { initializeApp, cert } from 'firebase-admin/app'
import { getFirestore } from 'firebase-admin/firestore'
import dotenv from 'dotenv'
dotenv.config()

// Firebase 初期化
function toISOStringIfTimestamp(value: any): string {
  if (!value) return ''
  if (typeof value.toDate === 'function') {
    return value.toDate().toISOString()
  }
  if (typeof value === 'string') {
    return new Date(value).toISOString()
  }
  return ''
}
const serviceAccount = JSON.parse(
  Buffer.from(process.env.FIREBASE_ADMIN_KEY_BASE64!, 'base64').toString('utf8')
)
initializeApp({ credential: cert(serviceAccount) })
const db = getFirestore()

// Google Sheets 認証
async function getSheetsClient() {
  const auth = new google.auth.GoogleAuth({
    credentials: {
      client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
      private_key: process.env.GOOGLE_PRIVATE_KEY!.replace(/\\n/g, '\n'),
    },
    scopes: ['https://www.googleapis.com/auth/spreadsheets'],
  })
  return google.sheets({ version: 'v4', auth })
}

async function exportPosts() {
  const sheets = await getSheetsClient()
  const sheetId = process.env.GOOGLE_SHEET_ID!
  const snapshot = await db
    .collection('posts')
    .orderBy('createdAt', 'desc')
    .get()

  const rows = snapshot.docs.map((doc) => {
    const data = doc.data()
    return [
      doc.id,
      data.title,
      data.slug,
      data.category,
      data.tags?.join(', ') || '',
      toISOStringIfTimestamp(data.createdAt),
      data.clickCount || 0,
      data.readCount || 0,
      data.score || 0,
      data.autoGenerated ? '✅' : '',
      data.variantId || 'A',
    ]
  })

  // ヘッダー行
  rows.unshift([
    'ID',
    'タイトル',
    'スラッグ',
    'カテゴリ',
    'タグ',
    '作成日',
    'クリック数',
    '読了数',
    'スコア',
    '自動生成？',
    'バリアント',
  ])

  await sheets.spreadsheets.values.update({
    spreadsheetId: sheetId,
    range: 'posts!A1',
    valueInputOption: 'RAW',
    requestBody: {
      values: rows,
    },
  })

  console.log('✅ Firestore → Sheets エクスポート完了')
}

exportPosts()
